# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CountrieOfTheWorld.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(571, 614)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidgetCountries = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetCountries.setGeometry(QtCore.QRect(10, 40, 256, 511))
        self.listWidgetCountries.setObjectName("listWidgetCountries")
        self.labelListWidget = QtWidgets.QLabel(self.centralwidget)
        self.labelListWidget.setGeometry(QtCore.QRect(10, 10, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelListWidget.setFont(font)
        self.labelListWidget.setObjectName("labelListWidget")
        self.frameHide = QtWidgets.QFrame(self.centralwidget)
        self.frameHide.setGeometry(QtCore.QRect(270, 20, 291, 531))
        self.frameHide.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameHide.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameHide.setObjectName("frameHide")
        self.labelDisArea = QtWidgets.QLabel(self.frameHide)
        self.labelDisArea.setGeometry(QtCore.QRect(170, 280, 91, 16))
        self.labelDisArea.setObjectName("labelDisArea")
        self.comboBoxAreaType = QtWidgets.QComboBox(self.frameHide)
        self.comboBoxAreaType.setGeometry(QtCore.QRect(70, 280, 81, 22))
        self.comboBoxAreaType.setObjectName("comboBoxAreaType")
        self.comboBoxAreaType.addItem("")
        self.comboBoxAreaType.addItem("")
        self.textEditDisPopulation = QtWidgets.QTextEdit(self.frameHide)
        self.textEditDisPopulation.setGeometry(QtCore.QRect(90, 230, 104, 31))
        self.textEditDisPopulation.setObjectName("textEditDisPopulation")
        self.labelPopulationTitle = QtWidgets.QLabel(self.frameHide)
        self.labelPopulationTitle.setGeometry(QtCore.QRect(0, 240, 81, 21))
        self.labelPopulationTitle.setObjectName("labelPopulationTitle")
        self.pushButtonUpdatePopulation = QtWidgets.QPushButton(self.frameHide)
        self.pushButtonUpdatePopulation.setGeometry(QtCore.QRect(50, 470, 141, 41))
        self.pushButtonUpdatePopulation.setObjectName("pushButtonUpdatePopulation")
        self.labelDisFlag = QtWidgets.QLabel(self.frameHide)
        self.labelDisFlag.setGeometry(QtCore.QRect(0, 40, 281, 141))
        self.labelDisFlag.setText("")
        self.labelDisFlag.setObjectName("labelDisFlag")
        self.labelTitlePopulationDensity = QtWidgets.QLabel(self.frameHide)
        self.labelTitlePopulationDensity.setGeometry(QtCore.QRect(20, 310, 151, 21))
        self.labelTitlePopulationDensity.setObjectName("labelTitlePopulationDensity")
        self.frame = QtWidgets.QFrame(self.frameHide)
        self.frame.setGeometry(QtCore.QRect(10, 320, 271, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.radioButtonPerSquareMile = QtWidgets.QRadioButton(self.frame)
        self.radioButtonPerSquareMile.setGeometry(QtCore.QRect(10, 20, 141, 17))
        self.radioButtonPerSquareMile.setChecked(True)
        self.radioButtonPerSquareMile.setAutoRepeat(False)
        self.radioButtonPerSquareMile.setObjectName("radioButtonPerSquareMile")
        self.radioButtonPerSquareKM = QtWidgets.QRadioButton(self.frame)
        self.radioButtonPerSquareKM.setGeometry(QtCore.QRect(10, 50, 131, 17))
        self.radioButtonPerSquareKM.setObjectName("radioButtonPerSquareKM")
        self.labelDisPopulationDensity = QtWidgets.QLabel(self.frame)
        self.labelDisPopulationDensity.setGeometry(QtCore.QRect(150, 30, 111, 21))
        self.labelDisPopulationDensity.setObjectName("labelDisPopulationDensity")
        self.labelTitleArea = QtWidgets.QLabel(self.frameHide)
        self.labelTitleArea.setGeometry(QtCore.QRect(0, 280, 61, 16))
        self.labelTitleArea.setObjectName("labelTitleArea")
        self.labelDisPercentOfWorld = QtWidgets.QLabel(self.frameHide)
        self.labelDisPercentOfWorld.setGeometry(QtCore.QRect(160, 420, 91, 21))
        self.labelDisPercentOfWorld.setToolTipDuration(-4)
        self.labelDisPercentOfWorld.setObjectName("labelDisPercentOfWorld")
        self.labelTitleCountryName = QtWidgets.QLabel(self.frameHide)
        self.labelTitleCountryName.setGeometry(QtCore.QRect(0, 0, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelTitleCountryName.setFont(font)
        self.labelTitleCountryName.setObjectName("labelTitleCountryName")
        self.labelTitlePercentOfWorld = QtWidgets.QLabel(self.frameHide)
        self.labelTitlePercentOfWorld.setGeometry(QtCore.QRect(10, 410, 131, 41))
        self.labelTitlePercentOfWorld.setWordWrap(True)
        self.labelTitlePercentOfWorld.setObjectName("labelTitlePercentOfWorld")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 571, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Countries = QtWidgets.QAction(MainWindow)
        self.actionLoad_Countries.setEnabled(True)
        self.actionLoad_Countries.setObjectName("actionLoad_Countries")
        self.menuFile.addAction(self.actionLoad_Countries)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelListWidget.setText(_translate("MainWindow", "Choose a country from the list"))
        self.labelDisArea.setText(_translate("MainWindow", "TextLabel"))
        self.comboBoxAreaType.setItemText(0, _translate("MainWindow", "Sq. Mi."))
        self.comboBoxAreaType.setItemText(1, _translate("MainWindow", "Sq. Km."))
        self.labelPopulationTitle.setText(_translate("MainWindow", "Population:"))
        self.pushButtonUpdatePopulation.setText(_translate("MainWindow", "Update Population"))
        self.labelTitlePopulationDensity.setText(_translate("MainWindow", "Population Density"))
        self.radioButtonPerSquareMile.setText(_translate("MainWindow", "Per Square Mile"))
        self.radioButtonPerSquareKM.setText(_translate("MainWindow", "Per Square KM"))
        self.labelDisPopulationDensity.setText(_translate("MainWindow", "TextLabel"))
        self.labelTitleArea.setText(_translate("MainWindow", "Area in"))
        self.labelDisPercentOfWorld.setText(_translate("MainWindow", "TextLabel"))
        self.labelTitleCountryName.setText(_translate("MainWindow", "countryname"))
        self.labelTitlePercentOfWorld.setText(_translate("MainWindow", " Perecntage of World Population:"))
        self.menuFile.setTitle(_translate("MainWindow", "file"))
        self.actionLoad_Countries.setText(_translate("MainWindow", "Load Countries"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

